In [1]:
import numpy as np

In [4]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [29]:
import antipackage
from github.ellisonbg.misc import vizarray as va

ImportError: cannot import name 'urlretrieve'

In [6]:
data = [0,2,4,6]
a = np.array(data)

In [7]:
type(a)

numpy.ndarray

In [8]:
a

array([0, 2, 4, 6])

In [9]:
a.shape

(4,)

In [10]:
a.ndim

1

In [11]:
a.size

4

In [12]:
a.nbytes

32

In [13]:
a.dtype

dtype('int64')

In [17]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0], [1.0,2.0,3.0,4.0]]
b = np.array(data)

In [18]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.],
       [ 1.,  2.,  3.,  4.]])

In [19]:
b.shape, b.ndim, b.size, b.nbytes

((3, 4), 2, 12, 96)

In [25]:
c = np.arange(0.0, 20.0, 2.0)
c

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [27]:
e = np.linspace(0.0, 9.0, 3)
e

array([ 0. ,  4.5,  9. ])

In [30]:
np.empty((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [33]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [53]:
a = np.array([1,2,3,4])

In [54]:
a, a.dtype

(array([1, 2, 3, 4]), dtype('int64'))

In [65]:
b = np.zeros((2,2), dtype=np.complex64)
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]], dtype=complex64)

In [69]:
c = np.arange(0, 20, 4, dtype=np.float)
c

array([  0.,   4.,   8.,  12.,  16.])

In [70]:
d = c.astype(dtype=np.int)
d

array([ 0,  4,  8, 12, 16])

In [84]:
np.float*?

In [88]:
a = np.empty((3,3), dtype=np.int64)
a.fill(6)
a

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [94]:
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [95]:
a+b

array([[ 7.,  7.,  7.],
       [ 7.,  7.,  7.],
       [ 7.,  7.,  7.]])

In [96]:
b/a

array([[ 0.16666667,  0.16666667,  0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667]])

In [97]:
a/b

array([[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

In [98]:
a**2

array([[36, 36, 36],
       [36, 36, 36],
       [36, 36, 36]])

In [99]:
np.pi*b

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [109]:
a = np.random.rand(6,6)

In [110]:
a[0,0]

0.83438918776281612

In [114]:
a[-1,-1] == a[5,5]

True

In [115]:
a[:,0]

array([ 0.83438919,  0.18034603,  0.55138011,  0.56378493,  0.53099761,
        0.1879156 ])

In [116]:
a[0:2,0:2]

array([[ 0.83438919,  0.29926102],
       [ 0.18034603,  0.66158539]])

In [117]:
a[0:5,0:5] = 1.0

In [118]:
a

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.48938767],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.12797526],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.08531904],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.78770196],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.97445815],
       [ 0.1879156 ,  0.86043708,  0.32280121,  0.75036672,  0.3508158 ,
         0.63288196]])

In [ ]:
ages = np.array([23,56,67,89,23,56,27,12,8,72])
genders = np.array(['m','m','f','f','m','f'])